version: 1.0.0.{build}
configuration: Release
platform: Any CPU
environment:
  COVERALLS_REPO_TOKEN:
    secure: //W45NFofQ/uvbUOP9N6vZZK9p3MHRkZDadhuEdqbBNNgmekPeehTMTqslqNmG+S
assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'
before_build:
- cmd: nuget restore
build:
  project: Limitless.ioRPC.sln
  verbosity: minimal
test_script:
- cmd: .\RunTestsWithCoverage.bat
after_test:
- cmd: .\SubmitCoverage.bat
